INSERT INTO MODULE VALUES(
	('120894', 'COMPUTER NETWORKING', 120);
	('213931', 'STRENGHTS OF MATERIALS', 120);
	('127042', 'FLIUD MECHANICS', 210);
	('120919', 'ARTIFICIAL INTELLIGENCE', 120);
	('321239', 'DATABASES', 120);
);

INSERT INTO STUDENT VALUES(
	();('2060221', 'M', 'Maher', 'Male', '02-12-2000', 'Mcabgee@gmail.com'); 
	();('2108418', 'AL', 'Alan' , 'Male', '14-08-2000', 'Alan2000@gmail.com');
	();('2094823', 'MG', 'Margaret', 'Female', '21-10-2002', 'Maggie12@gmail.com');
	();('2085762', 'ABI', 'ABIGAIL', 'FEMALE', '10-10-2004', 'Abigail2@gmail.com');
	();('2276876', 'A', 'Alex', 'MALE', '05-07-2001', 'Alex21@gmail.com');
	();('2567214', 'L', 'Lydia', 'Female', '22-11-2003', 'Lydiarose@gmail.com');
	();('2050551', 'D', 'Dilian', 'Male', '01-01-2001', 'Dilianwhyte@gmail.com');
	();('2040231', 'V', 'Velvet', 'Female', '02-10-2002', 'Velvet@gmail.com');
);

INSERT INTO COURSE VALUES(
	();(
	();
	();
	();
	();
);

INSERT INTO RESULTS VALUES(
	();
	();
	();
	();
	();
	();
	();
	();
);

INSERT INTO REGISTRATION VALUES(
	();
	();
	();
	();
	();
	();
	();
	();

);

/*
a. Some Modules may not have any Students allocated yet.
b. There may be some Students who have yet to enrol on a Module.
c. Some Courses may be new and not have any Students taking it.
d. A Student must be registered on a Course.
e. The test data should be appropriate to the queries requested (that 
is, no query should return “no rows retrieved”). 
Give  thought  to  what  data  should  be  added.  As  a  minimum,  each  table 
should have at least 5 rows in it, but some should be more, for example, 
you  may  have  5  modules,  but  each  module  should  have  at  least  5-6 
students  enrolled  on  it.  Basically,  the  tables  at  the  many  end  of  a 
relationship should therefore contain more data than the relation at the one 
end. 
*/